import React, { Fragment } from 'react'
import { Card} from 'antd';
import CardContainer from './components/CardContainer';
const form  = {
    "formTitle": "Unititled Form",
    "type":"google_forms",
    "designSystem":"ant.Design",
    "autoGenerated":{
        "sections": [
            {
               "title": "Section1",
               "description": "Section1 Description" ,
                "fieldCards": [
                    {
                        "type": "fieldCardType - Multiple Question",
                        "headingTitle": "Question 1", 
                        "headingDescription": "Question Description",
                        "required": ""
                    }
                ]
            },
            {
                "title": "Section2",
                "description": "Section2",
                "fieldCards": []
             },
             {
                "title": "Section3",
                "description": "Section3 Description" ,
                "fieldCards": []
             }
        ]
    }
}    

export default function AutoContainer() {

    return (
       <Fragment>
           {
                form.autoGenerated.sections.map(
                    section => (<CardContainer /> )
                        
                    
                )
           }
       </Fragment>
    )
}
